### ISSUE TITLE
This Application Needs New Domain  Code Added to nrwugspgressp domain GWDPLoggerType

### ISSUE THREAD

**Issue by inkenbrandt** [UGS-GIO/groundwaterMonPortal#37]
### Name of Existing Layer (as it appears in the application)

GWDPLoggerType

### Folder path of data

No path, just add a domain option

### Why do you feel this application needs what you're requesting?

We recently switched to a new type of datalogger, so we need to add this datalogger type to our domain.

- [ ] Code: Rugged Troll (Nonvented)  Description: All RUGGED nonvented In-Situ Troll Transducers, Including the barometers
- [ ] Code: Level Troll (Vented) Description: Vented In-situ Level Troll Transducers
- [ ] Code: Level Troll (Nonvented) Description: Non-vented In-situ Level Troll Transducers
- [ ] Code: Aqua Troll (Vented) Description: Vented In-situ Aqua Troll Transducer; measures Cond., Temp., and Level
- [ ] Code: Aqua Troll (Nonvented) Description: Non-vented In-situ Aqua Troll Transducer; measures Cond., Temp., and Level

### Who has reviewed your database so far (e.g. Schema, Field Types, Topology, etc.)?

Martha

### Who has reviewed your science and grammar so far?

Allot of people. My science is good and my grammar is gooder.

**Comment by marthajensen** [comment]
@inkenbrandt 

"Allot of people. My science is good and my grammar is gooder."

Deep belly laugh! hahhhahaha! I needed that!! thank you

**Comment by marthajensen** [comment]
@inkenbrandt done :)

**Comment by inkenbrandt** [comment]
Thanks Martha!
