### ISSUE TITLE
Suggest Static Text Edit

### ISSUE THREAD

**Issue by marshallrobinson** [UGS-GIO/groundwaterMonPortal#38]
### Where is the text you are suggesting changes for?

Info (?) Panel

### What does the current text say?

The Utah Geological Survey (UGS) developed the [Groundwater Monitoring Data Portal](https://apps.geology.utah.gov/gwdp/) to store and distribute large quantities of monitoring data acquired through the various monitoring networks that the UGS maintains. The portal allows easy access to view, query, and download groundwater monitoring data from a dataset containing more than 12 million records, including well and piezometer water-level records and spring and surface flow measurements. Individual wells or surface water monitoring locations may be selected and more information is available on their respective pages. Data may be viewed directly, downloaded in CSV format, or a well or spring summary report may be viewed or downloaded in PDF format. CSV files may be imported into Microsoft Excel or other software for further analysis and plotting. This application would not have been possible without the initial efforts of Kevin Thomas, Quinton Williams, Steve Bowman, Lucy Jordan, and Hugh Hurlow.

### What do you propose the new text says?

The Utah Geological Survey (UGS) developed the [Groundwater Monitoring Data Portal](https://apps.geology.utah.gov/gwdp/) to store and distribute large quantities of monitoring data acquired through the various monitoring networks that the UGS maintains. The portal allows easy access to view, query, and download groundwater monitoring data from a dataset containing more than 12 million records, including well and piezometer water-level records and spring and surface flow measurements. Individual wells or surface water monitoring locations may be selected and additional information is available to view when clicking on their respective "Site Details" button. Data may be viewed directly in the "Site Details" panel, downloaded in CSV format, or a well or spring summary report may be viewed or downloaded in PDF format. CSV files may be imported into Microsoft Excel or other software for further analysis and plotting. This application would not have been possible without the initial efforts of Kevin Thomas, Quinton Williams, Steve Bowman, Lucy Jordan, and Hugh Hurlow. Continued efforts from Paul Inkenbrandt, Lance Weaver, and Martha Jensen keep this application in working order.

### Who has reviewed your proposed text so far?

@inkenbrandt, what do you think of the proposed changes I made? Specifically, I'm not sure if the part about "or a well or spring summary report may be viewed or downloaded in PDF format." Is that applicable still?

**Comment by inkenbrandt** [comment]
Lance is still using the amCharts graphing functionality that Brian used, so the pdf export is still possible.  Lance should be moved up on the list of web developers as Brian's code is deprecated. https://geology.utah.gov/map-pub/maps/interactive-maps/groundwater-monitoring/

**Comment by inkenbrandt** [comment]
The other wording changes look great to me!

**Comment by marshallrobinson** [comment]
@inkenbrandt, I had Mackenzie forward https://geology.utah.gov/map-pub/maps/interactive-maps/groundwater-monitoring/ to skip straight to the application since what was on there before is now in the "about panel" in the application.

@lance-weaver, please change the text in the "about panel" to what's shown below in order to add in the information a bout the pdf report download. Also, please make the info panel be open when the application first loads.

The Utah Geological Survey (UGS) developed the Groundwater Monitoring Data Portal to store and distribute large quantities of monitoring data acquired through the various monitoring networks that the UGS maintains. The portal allows easy access to view, query, and download groundwater monitoring data from a dataset containing more than 12 million records, including well and piezometer water-level records and spring and surface flow measurements. Individual wells or surface water monitoring locations may be selected and additional information is available to view when clicking on their respective "Site Details" button. Data may be viewed directly in the "Site Details" panel, downloaded in CSV format, or a well or spring summary report may be viewed or downloaded in PDF format. CSV files may be imported into Microsoft Excel or other software for further analysis and plotting. This application would not have been possible without the initial efforts of Kevin Thomas, Quinton Williams, Steve Bowman, Lucy Jordan, and Hugh Hurlow. Continued efforts from Paul Inkenbrandt, Lance Weaver, and Martha Jensen keep this application in working order.

**Comment by lance-weaver** [comment]
Done
