### ISSUE TITLE
This Application Needs New Data Added to Well Info?

### ISSUE THREAD

**Issue by LucyJordan** [UGS-GIO/groundwaterMonPortal#43]
### Name of Existing Layer (as it appears in the application)

I don't know. Should be one of the well info layers.

### Folder path of data

I do not know

### Why do you feel this application needs what you're requesting?

The data in the Logger Type field is out of date and needs updating. This is especially important for these four sites because sometimes we have had loggers that can log electrical conductivity and some times we have not. If the field is long enough, can you please update the Logger Type field for wells 138, 139, 140, and 141 to the following?

138 (CHWENT):  Solinst levelogger 3-14-2012 to 10-16-2019; Solinst levelogger LTC 10-16-2019 to current 

139 (CHWNVJ): Solinst levelogger 3-14-2012 to 10-16-2019; Solinst levelogger LTC 10-16-2019 to 5-28-2021; logger malfunction 5-28-2021 to 10-7-2021; Solinst levelogger 10-7-2021 to 10-18-2022; In Situ AquaTroll 10-18-2022 to current

140 (SMCENT): Solinst levelogger 10-27-2020 to 7-17-2022; InSitu AquaTroll 7-17- 2022 to current
141 (SMCNVJ): Solinst levelogger 10-27-2020 to 7-17-2022;  InSitu AquaTroll 7-17- 2022 to current

### Who has reviewed your database so far (e.g. Schema, Field Types, Topology, etc.)?

@inkenbrandt 

### Who has reviewed your science and grammar so far?

@inkenbran

**Comment by marshallrobinson** [comment]
Martha will be in contact. Thanks for submitting.

**Comment by marthajensen** [comment]
@inkenbrandt @LucyJordan 

The logger type field is based on a domain. In order to change the data, I need to add the following domains to the database:

Solinst levelogger 3-14-2012 to 10-16-2019; Solinst levelogger LTC 10-16-2019 to current

Solinst levelogger 3-14-2012 to 10-16-2019; Solinst levelogger LTC 10-16-2019 to 5-28-2021; logger malfunction 5-28-2021 to 10-7-2021; Solinst levelogger 10-7-2021 to 10-18-2022; In Situ AquaTroll 10-18-2022 to current

Solinst levelogger 10-27-2020 to 7-17-2022; InSitu AquaTroll 7-17- 2022 to current

Solinst levelogger 10-27-2020 to 7-17-2022;  InSitu AquaTroll 7-17- 2022 to current


**_Are you two OK with me adding those 4 domains?_**

**Comment by marthajensen** [comment]
Oh woops - I meant 3 domains (one is a repeat)

**Comment by inkenbrandt** [comment]
I think those lines should be notes for the station, as they indicate an event in the station's history, which really goes beyond what that domained field is meant for. That field is used to indicate the current transducer type at the site.
We should add "Solinst Levelogger LTC" and "InSitu AquaTroll" as domains.

**Comment by inkenbrandt** [comment]
Alternatively, we could add those specific domains and make the application of the field more broad.

**Comment by marthajensen** [comment]
@inkenbrandt @LucyJordan Let me know what you decide to do and I will add this data to whichever field you like (either as a domain in loggertype or as notes in another field).  At that time, I can also add the "Solinst Levelogger LTC" and "InSitu AquaTroll" as domains

**Comment by LucyJordan** [comment]
I like the detailed logger notes to be in the notes field, perhaps keyed to a date if needed, and just add the two logger types "Solinst Levelogger LTC" and "InSitu AquaTroll" as domains, like @inkenbrandt  suggested. Currently three of the Moab wells have InSitu AquaTroll and CHWENT has Solinst Levelogger LTC.

**Comment by marthajensen** [comment]
@LucyJordan @inkenbrandt 

The data for these wells has been updated. I changed the logger type to the new one, then added the additional logger information to the Notes field.  Please let me know if these changes accomplished what you wanted. Below is a screenshot for CHWENT

![image](https://user-images.githubusercontent.com/11522897/203396766-75fb0b3d-456a-4bd4-ab86-8998aa14f92d.png)
