### ISSUE TITLE
This Application Needs New Data Added to Note Log for well 139 CHWNVJ

### ISSUE THREAD

**Issue by LucyJordan** [UGS-GIO/groundwaterMonPortal#44]
### Name of Existing Layer (as it appears in the application)

note log of well 139

### Folder path of data

I do not know

### Why do you feel this application needs what you're requesting?

A transducer malfunctioned in this well. Please add a note to the note log:

No water-level data collected from 28 May 2021 to 7 Oct 2021 due to transducer malfunction. 

### Who has reviewed your database so far (e.g. Schema, Field Types, Topology, etc.)?

@inkenbrandt 

### Who has reviewed your science and grammar so far?

@

**Comment by LucyJordan** [comment]
![image](https://user-images.githubusercontent.com/117779550/200690517-413c8a8b-94ae-46bf-b3b5-af857609c2cf.png)

I don't understand the difference between the note log and the note field. Seems like this kind of note should go in the note log, but there is a similar note in the note field.

**Comment by marthajensen** [comment]
done 
![image](https://user-images.githubusercontent.com/11522897/200698285-e327c9c8-f874-449d-a342-ef7e812ab35e.png)
