### ISSUE TITLE
Missing well

### ISSUE THREAD

**Issue by LucyJordan** [UGS-GIO/groundwaterMonPortal#48]
### What happened?

The National Park Service, our "client" for the Moab Courthouse Wash and Sevenmile Canyon wells, just emailed me the following. 

"Finally, FYI, I noticed that the Navajo completion of the Sevenmile Canyon monitoring well is not showing up on the [Groundwater Monitoring Data Portal](https://apps.geology.utah.gov/gwdp/). I don't think we anticipate needing updated data in the near future, but I just wanted to let you know in case this will take a while to fix."

The Courthouse wash multiple completion well is showing up just fine but something is broken with the Sevenmile Canyon well. please fix asap.  The well Name is SMCNVJ and the wellID is either one more or one less than the Entrada Completion. 
ID: 384022109400401
Name: SMCENT

### What did you expect to happen?

Site should come up with multiple wells to click through.

### Browser Version

Chrome Version 108.0.5359.95 (Official Build) (64-bit)

**Comment by inkenbrandt** [comment]
same issue as the springs;  need to update display field for these sites to
1

**Comment by LucyJordan** [comment]
Looks like this has been fixed and could be closed. @inkenbrandt
