### ISSUE TITLE
Ability to store and graph conductivity data

### ISSUE THREAD

**Issue by Stefankirby** [UGS-GIO/groundwaterMonPortal#5]
We need the ability to store and graph conductivity data at the courthouse wash site.

This would take the form of an additional numeric field in the database.  That could then be simply graphed.

**Comment by marthajensen** [comment]
Added a conductivity column to the existing readings table available at:
https://webmaps.geology.utah.gov/arcgis/rest/services/Groundwater/GWDP_V2/MapServer/12

**Comment by LucyJordan** [comment]
I would also like this. We need it for four sites, 138, 139, 140, and 141, to provide the data requested by the project funders, National Park Service.

**Comment by marshallrobinson** [comment]
Thanks, 
@lance-weaver, @marthajensen, and I will discuss what's needed to implement this and get back to you.

**Comment by LucyJordan** [comment]
Is there any progress on this? I have taken over the project from Stefan Kirby. I'm doing the annual report now and in last year's report we promised the NPS these conductivity data would be available on our data portal website. Can I give the NPS people a projected completion date? Thanks.

**Comment by marthajensen** [comment]
@LucyJordan 

We were discussing this issue this morning. Do you mind sending me the conductivity and temperature data for these wells?  Thanks!

**Comment by lance-weaver** [comment]
@LucyJordan       Also, we might need a little clarification on how exactly you'd like this presented in the web interface. Maybe a video chat sometime might be best to explain it?

**Comment by inkenbrandt** [comment]
The conductivity and temperature are fields in the `ugsgwp.sde.reading` table.  Temperature is populated, but is doesn't look like there are data in the conductivity field yet.

**Comment by inkenbrandt** [comment]
Courthouse Wash and Sevenmile Canyon Logger Log

Log of Logger Types installed in wells

Last saved by  Lucy Jordan  on 12/20/2022 10:45:00 AM


138 CHWENT  
Solinst levelogger 3-14-2012 to 10-16-2019; 
Solinst levelogger LTC 10-16-2019 to current 

139 CHWNVJ   
Solinst levelogger 3-14-2012 to 10-16-2019; 
Solinst levelogger LTC 10-16-2019 to 5-28-2021; 
logger malfunction 5-28-2021 to 10-7-2021; 
Solinst levelogger 10-7-2021 to 10-18-2022; 
In Situ AquaTroll 10-18-2022 to current

140 
SMCENT Solinst levelogger 10-27-2020 to 7-19-2022; 
InSitu AquaTroll 7-19- 2022 to current

141 SMCNVJ 
Solinst levelogger 10-27-2020 to 7-19-2022;  
InSitu AquaTroll 7-19- 2022 to current

**Comment by marthajensen** [comment]
Update on this enhancement:

Last Thursday, @inkenbrandt sent me the conductivity data for these wells. The data will be added to the 'conductivity' field in the "reading" table. This addition of data is a little more complex than usual because I have to add the data using both the readingdate and the locationid fields to update the data in the table.

**Comment by marshallrobinson** [comment]
> @LucyJordan Also, we might need a little clarification on how exactly you'd like this presented in the web interface. Maybe a video chat sometime might be best to explain it?

@LucyJordan, just making sure you saw this comment from Lance.

**Comment by LucyJordan** [comment]
Yes, sorry. Should have done it today but I got busy. I'm unavailable for video conf until Friday or can do next week. 
I think either a separate time series graph below the water level graph would be good or just put it on the water level graph using the secondary axis.

**Comment by LucyJordan** [comment]
@lance-weaver 
See thread above. All four of these wells have water level, temperature, and conductivity data. 
138 384149109400902 CHWENT
139 384149109400901 CHWNVJ
140 384022109400401 SMCENT
141 384022109400402 SMCNVJ 
@marthajensen said the conductivity data is in the 'conductivity' field in the "reading" table. I don't have access to those tables, but I'm betting temperature is there too. Conductivity is in units of microSiemens per centimeter, abbreviated uS/cm. If you have the ability to use Greek letters, replace the u with Greek letter mu.  Temperature is in Celsius.

**Comment by inkenbrandt** [comment]
Add `has_cond` field to `ugsgwp.sde.ugs_ngwmn_monitoring_locations` to designate if the well/spring has conductivity readings that need to be shown.

**Comment by inkenbrandt** [comment]
We are very close to having this wrapped up.  I think all that has to be done to leverage the new field Nate added and publish the resulting graphs on the main page.

**Comment by inkenbrandt** [comment]
Great!  Thanks for the update.

**Comment by LucyJordan** [comment]
It would be awesome if we had this up and running before March 30. I am
submitting a final report to National Park Service detailing our data for
these wells and if I could point users to the data portal, they will be
very pleased.
Lucy

**Comment by marshallrobinson** [comment]
This feature has been pushed to the live web application. The conductivity chart shows up beneath the groundwater elevation chart.

**Comment by LucyJordan** [comment]
So awesome. Thanks everyone!

[image: Photo]
[image: Facebook icon] <https://facebook.com/UTGeologicalSurvey>[image:
Twitter icon] <https://twitter.com/utahgeological>[image: Instagram icon]
<https://www.instagram.com/utahgeologicalsurvey/>[image: LinkedIn Icon]
<https://www.linkedin.com/company/utah-geological-survey>

J. Lucy Jordan, P.G. (she/her)
Senior Geologist
O/M: (801) 537-3347
E: ***@***.***

Utah Department of Natural Resources
Utah Geological Survey

geology.utah.gov
