### ISSUE TITLE
Data issue- incorrect/inconsistent locationid for Swanny Park

### ISSUE THREAD

**Issue by wetlandsDiane** [UGS-GIO/groundwaterMonPortal#61]
### Name of Existing Layer (as it appears in the application)

ugs_ngwmn_monitoring_locations and all related tables

### Folder path of data

NA

### Why do you feel this application needs what you're requesting?

Swanny Park site has different locationid in USGS NGWMN database compared to SDE database. USGS NGWMN has locationid 
383449109332201. SDE database has locationid 383440109331401. 

Paul should probably make this update and make sure to update either in both database or just in the cloud database when old database is deprecated

### Who has reviewed your database so far (e.g. Schema, Field Types, Topology, etc.)?

NA

### Who has reviewed your science and grammar so far?

NA

**Comment by inkenbrandt** [comment]
gw_write still does not have permission to access the `gwportal.ugs_ngwmn_monitoring_locations` table.


![image](https://github.com/user-attachments/assets/043110ff-bf0d-47f0-b091-d9e0b5290970)

**Comment by inkenbrandt** [comment]
Both databases have been updated
